services:
  db:
    image: postgres:16
    container_name: cfa_postgres
    environment:
      POSTGRES_DB: cfa
      POSTGRES_USER: cfa
      POSTGRES_PASSWORD: cfa
    ports:
      - "5432:5432"
    volumes:
      - cfa_pgdata:/var/lib/postgresql/data

volumes:
  cfa_pgdata:
