server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cfa
    username: cfa
    password: cfa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
ollama:
  base-url: http://localhost:11434
  model: mistral